.core-defs:
  variables:
    JNI_PATH: libretro-build
    MAKEFILE: Makefile.libretro
    CORENAME: mgba

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/vita-static.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/psp-static.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ps2-static.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/dingux-i386.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-jni.yml'

stages:
  - build-prepare
  - build-shared
  - build-static
  - test

#Desktop
libretro-build-linux-x64:
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs

libretro-build-windows-x64:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs

libretro-build-dingux-i386:
  extends:
    - .libretro-dingux-i386-make-default
    - .core-defs

# Android
android-armeabi-v7a:
  extends:
    - .libretro-android-jni-armeabi-v7a
    - .core-defs

android-arm64-v8a:
  extends:
    - .libretro-android-jni-arm64-v8a
    - .core-defs

android-x86_64:
  extends:
    - .libretro-android-jni-x86_64
    - .core-defs
    
android-x86:
  extends:
    - .libretro-android-jni-x86
    - .core-defs

# Static
libretro-build-libnx-aarch64:
  extends:
    - .libretro-libnx-static-retroarch-master
    - .core-defs

libretro-build-vita:
  extends:
    - .libretro-vita-static-retroarch-master
    - .core-defs
    
libretro-build-psp:
  extends:
    - .libretro-psp-static-retroarch-master
    - .core-defs

libretro-build-ps2:
  extends:
    - .libretro-ps2-static-retroarch-master
    - .core-defs
